### PR TITLE
Add monarch

### PR DESCRIPTION
**Pull request by thinknathan**
Adds [monarch](https://github.com/britzl/monarch)

### CODE REVIEW

**Comment by thejustinwalsh** [comment]
https://github.com/ts-defold/library/pull/53

**Comment by oivoodoo** [comment]
@thejustinwalsh somehow I missed this PR.

**Comment by thejustinwalsh** [comment]
No worries, just trying to cross-link the effort.
I am not using monarch, so any review / sanity check of the types is appreciated!

**Comment by thinknathan** [comment]
I'm going to go ahead and merge this. Feedback and follow-up PRs are very welcome!

**Pull request merged**
